### ISSUE TITLE
Remake of reloading

### ISSUE THREAD

**Issue by r-kaminski** [nokia-wroclaw/innovativeproject-inventory-of-supplies#120]
Reloading contents on web app should be done automatically (hard) OR there should be a button responsible for reloading only a portion of the site, e.g. supplies (easy).

**Comment by MarekPokropinski** [comment]
Added auto refresh on stocktakings details view. When supplies is checked or unchecked table refreshes.
Web app every second asks backend if report changed, and refreshes data if it did.
