### ISSUE TITLE
Searching

### ISSUE THREAD

**Issue by r-kaminski** [nokia-wroclaw/innovativeproject-inventory-of-supplies#2]
User is able to search supplies according to:
- [x] name of the supply

**Comment by MarekPokropinski** [comment]
Added searching by parts of supplies' names.
Added pagination to search results and to listing all supplies.
search endpoint is /api/supplies/search?name={part of name}&page={page number}&page_size={page size} 
Name is obligatory parameter.
If page is not provided it defaults to 1.
If page size is not provided it defaults to 10.

now response from /api/supplies and /api/supplies/search looks like this:
`{
    "next": "http://192.168.99.101/api/supplies/search?name=ab&page=2&page_size=2",
    "previous": null,
    "count": 52,
    "total_pages": 26,
    "results": [
        {
            "id": 113,
            "name": "Absolut Citron",
            "state": "",
            "description": ""
        },
        {
            "id": 675,
            "name": "Cabbage - Green",
            "state": "",
            "description": ""
        }
    ]
}`
