### ISSUE TITLE
Backend should wait for DB to accept connections

### ISSUE THREAD

**Issue by r-kaminski** [nokia-wroclaw/innovativeproject-inventory-of-supplies#36]
**UPDATE:** task has been partially done (backend will wait 1 second for database to wire up), but might be improved with Dockerize.

During development sometimes it is needed to wipe out database contents. It can be done by running:
`docker-compose stop`
`docker-compose rm`
`docker-compose up --force-recreate`

While starting with /clean/ containers  (3rd command above), backends tends to start connection before DB is set up.
`db_1        | 2019-03-20 15:37:24.204 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432`

`db_1        | 2019-03-20 15:37:24.204 UTC [1] LOG:  listening on IPv6 address "::", port 5432`

`backend starts connection now, but fails`

`db_1        | 2019-03-20 15:37:24.382 UTC [1] LOG:  database system is ready to accept connections`

**The goal of this task is to make backend wait for DB to set up it's inner service completety.**

[This](https://medium.com/@marcelorlima/how-to-easily-make-your-container-waits-for-another-one-to-get-up-with-dockerize-be392e4e8e23) article and [this](https://github.com/jwilder/dockerize) tool might be helpful.

**Comment by MarekPokropinski** [comment]
Temporary solution: made backend start after some constant amount of time after database.
