### ISSUE TITLE
Printing QR / barcodes

### ISSUE THREAD

**Issue by r-kaminski** [nokia-wroclaw/innovativeproject-inventory-of-supplies#8]
User is be able to print QR / barcodes by using:
- [x] regular printer

**Comment by MarekPokropinski** [comment]
Allows user to add supplies to printing queue and print them.
You add item to queue by pressing printer button next to item on supplies view. To view queue you have to click printer button on top toolbar.
In printing queue you can remove items from queue and you can print all items in queue.
After printing you can clear queue.
Every user has his own queue.
