### ISSUE TITLE
Mobile app list view refresh bug

### ISSUE THREAD

**Issue by r-kaminski** [nokia-wroclaw/innovativeproject-inventory-of-supplies#96]
Whenever user scrolls through list view of supplies or inventory reports, the view is being refreshed very often (after minimal scroll up/down), which makes UX cumbersome.
Either the refresh behavior should be fixed or pagination implemented in it's place (https://github.com/nokia-wroclaw/innovativeproject-inventory-of-supplies/issues/64)

Moreover, this warning should be fixed: `[Unhandled promise rejection: TypeError: _this._onRefresh is not a function. (In '_this._onRefresh()', '_this._onRefresh' is undefined)]`

**Comment by MarekPokropinski** [comment]
Added refreshing to components.
